
name: Push to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    if: github.repository == 'alexcoder04/awesome-nspire'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Push
      run: |
        git config user.name "${{ github.repository_owner }}"
        git config user.email "${{ github.repository_owner }}@protonmail.com"
        git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ github.repository }}.git"
        git push gitlab main:main
